# Generated by Django 4.0.6 on 2022-08-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBOperations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
