# Generated by Django 4.0.6 on 2022-09-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0002_employee_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prrdId', models.IntegerField(primary_key=True, serialize=False)),
                ('prdname', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
