# Generated by Django 4.0.6 on 2022-09-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='revision/images/'),
        ),
    ]
