# Generated by Django 4.0.6 on 2022-09-20 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0007_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prrdId',
            new_name='prdId',
        ),
    ]
